# Generated by Django 4.2 on 2023-07-14 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Destinatarios_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Destinatarios_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'destinatarios',
                'verbose_name_plural': 'destinatarios',
                'db_table': 'destinatarios',
            },
        ),
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=650)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(max_length=50)),
                ('formato', models.CharField(max_length=50)),
                ('dir', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Archivos_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Archivos_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'archivos',
                'verbose_name_plural': 'archivos',
                'db_table': 'archivos',
            },
        ),
    ]
