# Generated by Django 4.2.3 on 2023-07-16 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0003_alter_personas_identificacion_alter_personas_sexo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinatarios',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinatario_estado', to='mensajeria.maestras'),
        ),
    ]
