# Generated by Django 4.2.3 on 2023-07-16 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0005_chatgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatGroup',
        ),
    ]
