# Generated by Django 4.2 on 2023-07-17 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensajeria', '0006_delete_chatgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria',
            name='celular',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='mensajeria',
            name='conversacion_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mensajeria',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajeria_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensajeria',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajeria_estado', to='mensajeria.maestras'),
        ),
        migrations.AlterField(
            model_name='mensajeria',
            name='mensaje_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mensajeria',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mensajeria',
            name='recipiente_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mensajeria',
            name='timestamp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
