# Generated by Django 4.2 on 2023-07-17 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0007_alter_mensajeria_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeria',
            name='destinatarios_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mensajeria_destinatarios', to='mensajeria.destinatarios'),
        ),
    ]
