# Generated by Django 4.2 on 2023-07-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0009_rename_destinatarios_id_mensajeria_destinatario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=191, null=True)),
            ],
            options={
                'db_table': 'peticion',
            },
        ),
    ]
