# Generated by Django 4.2 on 2023-07-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0010_peticion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticion',
            name='estado',
            field=models.CharField(blank=True, max_length=1091, null=True),
        ),
    ]
