# Generated by Django 4.2.3 on 2023-07-17 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0012_mensajeria_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeria',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajeria_tipo', to='mensajeria.maestras'),
        ),
    ]
