# Generated by Django 4.2.3 on 2023-07-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0013_mensajeria_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeria',
            name='multimedia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
