# Generated by Django 4.2.3 on 2023-07-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0014_mensajeria_multimedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajeria',
            old_name='multimedia',
            new_name='sha256',
        ),
        migrations.AddField(
            model_name='mensajeria',
            name='multimedia_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
