# Generated by Django 4.2.3 on 2023-07-19 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0016_mensajeria_mime_type_alter_mensajeria_multimedia_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajeria',
            old_name='timestamp',
            new_name='timestamp_w',
        ),
    ]
