# Generated by Django 4.2.3 on 2023-07-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0017_rename_timestamp_mensajeria_timestamp_w'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeria',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
