# Generated by Django 4.2.3 on 2023-07-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0018_mensajeria_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeria',
            name='filename',
            field=models.TextField(blank=True, null=True),
        ),
    ]
