# Generated by Django 4.2.3 on 2023-07-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0020_mensajeria_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria',
            name='voice',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
