# Generated by Django 4.2.3 on 2023-07-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0021_alter_mensajeria_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeria',
            name='context_from',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='mensajeria',
            name='context_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
