# Generated by Django 4.2.3 on 2023-08-05 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensajeria', '0022_mensajeria_context_from_mensajeria_context_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Conversaciones_created_by', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Conversaciones_destinatarios', to='mensajeria.destinatarios')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Conversaciones_estado', to='mensajeria.maestras')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Conversaciones_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conversaciones',
                'verbose_name_plural': 'conversaciones',
                'db_table': 'conversaciones',
            },
        ),
    ]
