# Generated by Django 4.2.3 on 2023-08-05 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0023_conversaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria',
            name='conversacion_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mensajeria_conversaciones', to='mensajeria.conversaciones'),
        ),
    ]
