# Generated by Django 4.2.3 on 2023-08-05 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0025_rename_conversacion_id_mensajeria_conversacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinatarios',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Personas_destinatarios_persona', to='mensajeria.personas', unique=True),
        ),
    ]
