# Generated by Django 4.2.3 on 2023-08-05 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0026_alter_destinatarios_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversaciones',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Conversaciones_destinatarios', to='mensajeria.destinatarios', unique=True),
        ),
    ]
