version: "3.1"

services:
  db:
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_DATABASE: masiva
      MYSQL_USER: masiva
      MYSQL_PASSWORD: masiva
      MYSQL_ROOT_PASSWORD: masiva
    ports:
      - "3307:3306"
    expose:
      - "3306"
    networks:
      - local
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - my-db:/var/lib/mysql
    healthcheck:
      test: '/usr/bin/mysql --user=masiva --password=masiva --database=masiva --execute "SELECT * FROM auth_user;"'
      interval: 30s
      timeout: 10s
      retries: 6

  masiva:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_NAME: masiva
      DB_USER: masiva
      DB_PASSWORD: masiva
      DB_HOST: db
      DB_PORT: 3306
      SECRET_KEY: 2d_y^cbrb6fy7b(tq+90bmyc8(i7=m*p+3(7=k8xe^%m-bx988
      ID_WHATSAPP_BUSINESS: 115904928131631
      ID_WHATSAPP_NUMBER: 118294544557141
      API_VERSION_WHATSAPP: v18.0
      API_KEY: EAACkvj6jM9sBOZBPsvQd6XSmGaljRzhZAgvzczpRCBYNomaNRZAEx1fD3sgklKylfOt7L0CT8ZC3IORYsKpGidK91smXoBkqUc8olbE0jsxEt13vL5upH6wySGygy3PDIlkm3dCwyVBeEe6q774mJoBkdm248NCpbCtuwhA4pRbWNNUi3wi3JjJc5hVeeJa8ZBqgokd4gBAzvtTBT
    ports:
      - 8000:8000
    links:
      - db
    volumes:
      - ./:/app/
    healthcheck:
      test: '/usr/bin/mysql --user=masiva --password=masiva --database=masiva --execute "SELECT * FROM auth_user;"'
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - local

  # ngrok:
  #   image: ngrok/ngrok:latest
  #   depends_on:
  #     - masiva
  #   restart: unless-stopped
  #   command:
  #     - "start"
  #     - "--all"
  #     - "--config"
  #     - "/etc/ngrok.yml"
  #   volumes:
  #     - ${PWD}/ngrok.yml:/etc/ngrok.yml
  #   ports:
  #     - 4040:4040
  #   expose:
  #     - 4040

volumes:
  my-db:
networks:
  local:
