name: CD
on:
  push:
    branches: main
jobs:
  createcd:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Configura aws credentials
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "${{secrets.REMOTE_HOST}}"
          REMOTE_USER: "${{secrets.REMOTE_USER}}"
          TARGET: "${{secrets.TARGET}}"
